### PR TITLE
Fix current location button bug, Unit tests for origin and destination points component

### LINKED ISSUE #148: Bug Report: The "My Location" selection button remains visible on the screen even after being selected
### Description
The user can select any location as the origin point, including their current location.

### Expected Behavior
After selecting a location as the origin or destination, the app should exit editing mode and allow the user to proceed to the next step.

### Actual Behavior
The "My Location" button remains visible after selection.

Image

### PR DESCRIPTION
**Pull request by 7awraaa**
### New Features
- Unit tests for the StartAndDestinationPoints component

### Improvements
- Closes #148 
- Selecting the "My Location" button now exits editing mode, allowing the user to proceed to the next step.

https://github.com/user-attachments/assets/6f1415b4-c2b5-419f-9fc9-3a321adbf1c1

### CODE REVIEW

File: myApp/app/components/StartAndDestinationPoints.tsx [hunk 1]
```diff
@@ -96,23 +101,29 @@ const StartAndDestinationPoints: React.FC<Props> = ({ setOriginLocation, setDest
...
+                                    setShowMyLocButton(false);
+                                    setIsInputFocused(false);
+                                    
                                 } else {
-                                    console.log("User  location not available.");
+                                    console.log("User location not available.");
                                 }
                             }}
                             style={myLocationStyles.myLocationButton}
+
```
Comment (samjamhen) [inline myApp/app/components/StartAndDestinationPoints.tsx:112]: I think we should try to avoid unnecessary whitespace

File: myApp/app/components/StartAndDestinationPoints.tsx [hunk 2]
```diff
@@ -96,23 +101,29 @@ const StartAndDestinationPoints: React.FC<Props> = ({ setOriginLocation, setDest
...
                                 }
                             }}
                             style={myLocationStyles.myLocationButton}
+                            
                         >
                             <Icon name="target-two" size={20} color="black" />
                             <Text style={myLocationStyles.myLocationText}>  My Location</Text>
                         </TouchableOpacity>
                     )}
+
```
Comment (samjamhen) [inline myApp/app/components/StartAndDestinationPoints.tsx:118]: Same as comment above

File: myApp/app/components/StartAndDestinationPoints.tsx [hunk 3]
```diff
@@ -29,6 +28,7 @@ const StartAndDestinationPoints: React.FC<Props> = ({ setOriginLocation, setDest
     const [isOriginSet, setIsOriginSet] = useState(false);
     const [isInputFocused, setIsInputFocused] = useState(false); 
     const defaultTravel = 'TRANSIT';
+    const [showMyLocButton, setShowMyLocButton] = useState(true);
```
Comment (samjamhen) [inline myApp/app/components/StartAndDestinationPoints.tsx:31]: Nice catch for this fix! We'll now have better control on whether we want to display the location button or not

**Review by samjamhen — APPROVED** [review]

File: myApp/app/components/StartAndDestinationPoints.tsx (hunk 1 above)
Comment (7awraaa) [reply myApp/app/components/StartAndDestinationPoints.tsx]: You're right! White spaces have been removed.
